# Generated by Django 4.2.4 on 2023-08-18 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default='', max_length=250)),
                ('email', models.CharField(blank=True, default='', max_length=250)),
                ('telephone_nr', models.CharField(blank=True, default='', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('website', models.URLField()),
                ('email', models.CharField(blank=True, default='', max_length=250)),
                ('telephone_nr', models.CharField(blank=True, default='', max_length=250)),
                ('user_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_nr', models.IntegerField(default=0)),
                ('min_pers', models.IntegerField(default=0)),
                ('max_pers', models.IntegerField(default=0)),
                ('duration_hours', models.IntegerField(default=0)),
                ('min_time', models.TimeField()),
                ('max_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_id', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField()),
                ('arrival_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('comments', models.CharField(blank=True, default='', max_length=2500)),
                ('paid', models.BooleanField()),
                ('paid_amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.customers')),
                ('restaurant', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
                ('table', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.tables')),
            ],
        ),
    ]
