# Generated by Django 4.2.4 on 2023-08-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_rename_restaurant_id_tables_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
