# Generated by Django 4.2.4 on 2023-08-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0003_reservations_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='open_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='open_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CustomRestaurantAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('open', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
            ],
        ),
    ]
