# Generated by Django 4.2.4 on 2023-08-20 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_restaurants_open_friday_restaurants_open_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customrestaurantavailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='customrestaurantavailability',
            name='start_time',
        ),
    ]
