# Generated by Django 4.2.4 on 2023-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_remove_customrestaurantavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
