# Generated by Django 4.2.4 on 2023-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_restaurants_closing_time_restaurants_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='max_time',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='min_time',
        ),
        migrations.AddField(
            model_name='customrestaurantavailability',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='customrestaurantavailability',
            name='start_time',
            field=models.TimeField(default='10:00'),
        ),
    ]
