# Generated by Django 4.2.4 on 2023-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0007_remove_tables_max_time_remove_tables_min_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrestaurantavailability',
            name='end_time',
            field=models.TimeField(default='23:59'),
        ),
    ]
