# Generated by Django 4.2.4 on 2023-08-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0008_alter_customrestaurantavailability_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='duration_hours',
        ),
        migrations.AddField(
            model_name='customrestaurantavailability',
            name='meal_duration',
            field=models.IntegerField(default=0),
        ),
    ]
