# Generated by Django 4.2.4 on 2023-08-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0011_userrestaurantlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='number_of_persons',
            field=models.IntegerField(default=0),
        ),
    ]
