# Generated by Django 4.2.4 on 2023-08-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0012_reservations_number_of_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='payment_per_booking',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
