# Generated by Django 4.2.4 on 2023-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0015_alter_customrestaurantavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='reservation_date',
            field=models.DateField(),
        ),
    ]
