# Generated by Django 4.2.4 on 2023-09-20 11:17

import bookingsystem.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0016_alter_reservations_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('course_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentFrequencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('amount_of_months', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='restaurants',
            name='discount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.CreateModel(
            name='RestaurantSubscriptionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
                ('subscription', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.subscriptions')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('photo', models.ImageField(upload_to=bookingsystem.models.dish_photo_upload_path)),
                ('dish_order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.courses')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants'),
        ),
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.restaurants')),
            ],
        ),
    ]
