# Generated by Django 4.2.4 on 2023-09-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0017_courses_paymentfrequencies_subscriptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='payment_frequency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookingsystem.paymentfrequencies'),
        ),
    ]
