# Generated by Django 4.2.4 on 2023-09-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0018_restaurants_payment_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='paid_amount',
        ),
        migrations.AddField(
            model_name='reservations',
            name='created_by_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
