# Generated by Django 4.2.4 on 2023-09-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0023_alter_restaurants_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='country',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='place',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='postal_code',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='email',
            field=models.CharField(default='', max_length=250),
        ),
    ]
