# Generated by Django 4.2.4 on 2023-09-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0024_restaurants_address_restaurants_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='closing_time',
            new_name='closing_time_friday',
        ),
        migrations.RenameField(
            model_name='restaurants',
            old_name='opening_time',
            new_name='opening_time_friday',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_monday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_saturday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_sunday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_thursday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_tuesday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='closing_time_wednesday',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_monday',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_saturday',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_sunday',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_thursday',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_tuesday',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='opening_time_wednesday',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
