# Generated by Django 4.2.4 on 2023-09-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0025_rename_closing_time_restaurants_closing_time_friday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='front_page_text',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
