# Generated by Django 4.2.4 on 2023-09-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0026_restaurants_front_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='front_page_text',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
