# Generated by Django 4.2.4 on 2023-10-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0028_alter_customrestaurantavailability_end_time_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
